args = commandArgs(trailingOnly = T)

if(length(args) != 3 ){
stop("Usage: [phenotype.emmax] [genotype] [output.tsv]")
}
library(Matrix)
library(parallel)

n.cores = 10

phenotype = args[1]
genotype = args[2]
output = args[3]
#output = "01.C3.all.snp.1e-4.GT.R2"
#phenotype = "../02.total/01.emmax/00.pheno/02.C3.emmax" #same format as emmax
#genotype = "01.C3.all.snp.1e-4.GT" #can be generated by plink and tpedTo012.pl 


n.cores = 10
X = read.table(genotype, row.names = 1, head =T)
y = read.table(phenotype, row.names = 1, head =F)
y = y[colnames(X), 2]

X = as.matrix(X)
snp.R2 = mclapply(1:nrow(X), function(k){
fit = lm(y~ factor(X[k,]))
#fit.anova = anova(fit)
#summary(fit.anova)
#R2 = fit.anova$`Sum Sq`[1]/sum(fit.anova$`Sum Sq`)
summary(fit)$r.squared
#summary(fit)$adj.r.squared
}, mc.cores = n.cores)

snp.R2 = data.frame(unlist(snp.R2))
rownames(snp.R2) = rownames(X); colnames(snp.R2) = "R2"
head(snp.R2)
write.table(snp.R2, file = output, row.names = T, quote = F)